import {Prodn1} from "./prodn1";
import {Prodn3} from "./prodn3";
export class Data {
  id: string;
  lankod: string;
  arbetsplatskod: string;
  ao3: string;
  ansvar: string;
  frivilligUppgift: string;
  agarform: string;
  vardform: string;
  verksamhet: string;
  // sorteringskodProd: string;
  sorteringskodBest: string;
  prodn1: Prodn1;
  prodn3: Prodn3;
  benamning: string;
  benamningKort: string;
  postnr: string;
  postort: string;
  postadress: string;
  lakemedkomm: string;
  kontaktAkod: string;
  leverans: string;
  fakturering: string;
  anmarkning: string;
  fromDatum: string;
  tillDatum: string;
  regDatum: Date;
  ersattav: string;
  userId: string;
  arbetsplatskodlan: string;
  namn: string;
  andringsdatum: string;
  kommun: string;
  slask: string;
  apodos: string;
  externfaktura: string;
  kommunkod: string;
  externfakturamodell: string;
  vgpv: string;
  hsaid: string;
  userIdNew: string;
  deletable: boolean;
  groupCode: boolean;
  hsaidMissingInKiv: boolean;
}
